
service: aws-lambda-nodejs

provider:
  name: aws
  runtime: nodejs18.x
  region: eu-north-1
  environment:
    USERS_TABLE: UsersTable
    SECRET_KEY: ${env:SECRET_KEY}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:Query
        - dynamodb:PutItem
      Resource:
        - arn:aws:dynamodb:eu-north-1:867344453761:table/UsersTable


custom:
  documentation:
    version: 1.0.0
    title: Pohlman Protean API
    description: API to manage users and data.
    tags:
      - name: UsersTable
        description: Endpoints related to user management.

functions:
  - ${file(functions/createUser.yml)}
  - ${file(functions/getUser.yml)}
  - ${file(functions/getUsers.yml)}
  - ${file(functions/deleteUser.yml)}
  - ${file(functions/loginUser.yml)}

resources:
  Resources:
    ${file(resources/usersTable.yml)}

plugins:
  - serverless-offline
  - serverless-openapi-documentation